#!/usr/bin/env bash
#
# Execute a command in each subfolder.
#

get_bundle_dependencies()
{
	echo "fp-cli/fp-cli-bundle"
	curl --silent "https://raw.githubusercontent.com/fp-cli/fp-cli-bundle/main/composer.json" \
		| jq --raw-output '."require" | keys[] | select(startswith("fp-cli/"))'
}

while read -r dependency; do
	# Remove fp-cli/ prefix
    repo_path="${dependency:7}"
    if [ ! -d "${repo_path}" ]; then
		continue
	fi

	echo "--- ${repo_path}: ---"
	cd "${repo_path}"
	bash -c "$@"
	cd -
done <<< "$(get_bundle_dependencies)"
